theme: jekyll-theme-leap-day
tittl: Welcome to Project Semester 2 Assignment
description: This page was created as part of our assignment to have a blog in which you can read about wat we have done during this project
